### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch'

### ISSUE THREAD

**Issue by yyxxyykx** [FishMaster93/AFFIA3K#1]
学长您好！
我在运行train_fish代码的时候出现了以下错误：

Traceback (most recent call last):
  File "E:/ucii/AFFIA3K-main/train_Fish.py", line 13, in <module>
    from pytorch.evaluate import Evaluator
ModuleNotFoundError: No module named 'pytorch'

但是torch库是安装好了的，就报错没有pytorch，请问是什么原因呢？

**Comment by FishMaster93** [comment]
你好，这个代码是我入门时候写的，Evaluator是评估函数已经上传了！

**Comment by FishMaster93** [comment]
> 学长您好！ 我在运行train_fish代码的时候出现了以下错误：
> 
> Traceback (most recent call last): File "E:/ucii/AFFIA3K-main/train_Fish.py", line 13, in from pytorch.evaluate import Evaluator ModuleNotFoundError: No module named 'pytorch'
> 
> 但是torch库是安装好了的，就报错没有pytorch，请问是什么原因呢？

已经上传了代码

**Comment by yyxxyykx** [comment]
学长您好，打扰了！

Traceback (most recent call last):
  File "E:/ucii/AFFIA3K-main/train_Fish.py", line 8, in <module>
    from pytorch.losses import get_loss_func
ModuleNotFoundError: No module named 'pytorch'
这里同样也是安装了torch，但是pytorch报错了，请问您是不是同样有东西没放上来呢？

**Comment by FishMaster93** [comment]
> 学长您好，打扰了！
> 
> Traceback (most recent call last): File "E:/ucii/AFFIA3K-main/train_Fish.py", line 8, in from pytorch.losses import get_loss_func ModuleNotFoundError: No module named 'pytorch' 这里同样也是安装了torch，但是pytorch报错了，请问您是不是同样有东西没放上来呢？
pytorch是自己写的包，已经上传了，你查看下

**Comment by yyxxyykx** [comment]
抱歉，又来麻烦您了，发现了有几个问题
1.Traceback (most recent call last):
  File "E:/ucii/AFFIA3K-main/train_Fish.py", line 21, in <module>
    from early_stopping import save_model
ImportError: cannot import name 'save_model' from 'early_stopping' (D:\anaconda\envs\yyx1\lib\site-packages\early_stopping\__init__.py
请问这个save_model是您自己定义的吗？

2.
from pytorch.models import Cnn14, Cnn4,Cnn6, Cnn10, ResNet22, ResNet38, ResNet54, MobileNetV1, MobileNetV2
from panns import PANNS_Cnn10, PANNS_Cnn6, PANNS_Cnn14
from models.AudioNet import BC_ResNet, AudioNet
在这两行代码下面同样显示相应的函数没有定义，Cnn4,第二行的三个函数和下面的第三行的三个函数都没有定义
请您方便的话看看，非常感谢学长！

**Comment by FishMaster93** [comment]
> 抱歉，又来麻烦您了，发现了有几个问题 1.Traceback (most recent call last): File "E:/ucii/AFFIA3K-main/train_Fish.py", line 21, in from early_stopping import save_model ImportError: cannot import name 'save_model' from 'early_stopping' (D:\anaconda\envs\yyx1\lib\site-packages\early_stopping__init__.py 请问这个save_model是您自己定义的吗？
> 
> 
> from pytorch.models import Cnn14, Cnn4,Cnn6, Cnn10, ResNet22, ResNet38, ResNet54, MobileNetV1, MobileNetV2 from panns import PANNS_Cnn10, PANNS_Cnn6, PANNS_Cnn14 from models.AudioNet import BC_ResNet, AudioNet 在这两行代码下面同样显示相应的函数没有定义，Cnn4,第二行的三个函数和下面的第三行的三个函数都没有定义 请您方便的话看看，非常感谢学长！

全部上传了，这是很简单的任务，建议还是多写多理解，代码从https://github.com/qiuqiangkong/audioset_tagging_cnn借鉴！！
